#!/usr/bin/with-contenv sh

# copy mail notify script
[[ ! -f /config/mail-notification.sh ]] && \
  cp /defaults/mail-notification.sh /config/mail-notification.sh

# configure ssmtp
sed -i "s|^mailhub=mail|mailhub=${SMTP_SERVER}:${SMTP_PORT:-25}|" /etc/ssmtp/ssmtp.conf
if ! grep 'FromLineOverride=yes' /etc/ssmtp/ssmtp.conf; then
  echo 'FromLineOverride=yes' >> /etc/ssmtp/ssmtp.conf
fi
#   auth
if [ -n "${SMTP_USERNAME}" -a -n "${SMTP_PASSWORD}" ]; then
  if ! grep 'AuthUser=' /etc/ssmtp/ssmtp.conf; then
    echo "AuthUser=${SMTP_USERNAME}" >> /etc/ssmtp/ssmtp.conf
  fi
  if ! grep 'AuthPass=' /etc/ssmtp/ssmtp.conf; then
    echo "AuthPass=${SMTP_PASSWORD}" >> /etc/ssmtp/ssmtp.conf
  fi
  if ! grep 'AuthMethod=' /etc/ssmtp/ssmtp.conf; then
    echo 'AuthMethod=LOGIN' >> /etc/ssmtp/ssmtp.conf
  fi
fi
#   ssl
if [ -n "${SMTP_STARTTLS}" -a "${SMTP_STARTTLS}" = "yes" ] && ! grep 'UseSTARTTLS=Yes' /etc/ssmtp/ssmtp.conf; then
  echo 'UseSTARTTLS=Yes' >> /etc/ssmtp/ssmtp.conf
fi
if [ -n "${SMTP_SSL}" -a "${SMTP_SSL}" = "yes" ] && ! grep 'UseTLS=Yes' /etc/ssmtp/ssmtp.conf; then
  echo 'UseTLS=Yes' >> /etc/ssmtp/ssmtp.conf
fi

# permissions
chown transmission:transmission \
  /config/mail-notification.sh

chmod 755 \
  /config/mail-notification.sh
